FROM maven:3.6.3-openjdk-17 AS build


WORKDIR /app


COPY . .


RUN mvn clean install


EXPOSE 8080


EXPOSE 61616 8161


CMD ["java", "-jar", "target/fum-cloud-notification-core-0.0.1-SNAPSHOT.jar"]